-- 002 was generated by `@better-auth/cli`, which stopped at 1.5 while the
-- library we import is 1.7. The skew cost us exactly one column, and every
-- sign-up failed with `column "issuer" of relation "account" does not exist`.
--
-- The generator now reads better-auth's own table definitions instead, so this
-- cannot recur: see src/db/gen-auth-schema.ts. 002 is left as the record of
-- what was actually applied; this brings both a fresh and an existing database
-- to the same shape.

alter table "account" add column if not exists "issuer" text;

-- no rows exist yet, but a backfill costs nothing and makes this safe to run
-- against a database that already has accounts
update "account" set "issuer" = "providerId" where "issuer" is null;

alter table "account" alter column "issuer" set not null;
