import { access, readFile, rename, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import { defineConfig } from 'vite'
import type { Connect, Plugin, ViteDevServer } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

const DOCS = fileURLToPath(new URL('../../docs/', import.meta.url))
/** reproductions sit in docs/, the primitives in docs/examples/ */
const ROOTS = [DOCS, join(DOCS, 'examples')]

/**
 * Where a document's file already lives. Writing back to the file we read from
 * matters: guessing docs/ for a primitive would silently fork it into a second
 * copy that nothing loads.
 */
async function locate(slug: string, kind: 'stage' | 'anim'): Promise<string> {
  const name = `${slug}.${kind}.json`
  for (const root of ROOTS) {
    const path = join(root, name)
    try {
      await access(path)
      return path
    } catch { /* try the next root */ }
  }
  return join(DOCS, name)
}
/**
 * Documents were generated by different scripts and do not share an indent:
 * docs/ is one space, docs/examples/ is two. Reuse whatever the file already
 * has so a one-value edit produces a one-line diff instead of reformatting the
 * whole film.
 */
async function indentOf(path: string, fallback = 1): Promise<number> {
  try {
    const head = (await readFile(path, 'utf8')).slice(0, 200)
    const m = head.match(/^\{\r?\n( +)"/)
    return m ? m[1].length : fallback
  } catch {
    return fallback
  }
}

function body(req: Connect.IncomingMessage): Promise<string> {
  return new Promise((res, rej) => {
    let out = ''
    req.on('data', (c: Buffer) => {
      out += c
      if (out.length > 8_000_000) rej(new Error('document too large'))
    })
    req.on('end', () => res(out))
    req.on('error', rej)
  })
}

/** write through a temp file so an interrupted save cannot truncate a doc */
async function writeAtomic(path: string, text: string) {
  const tmp = `${path}.tmp`
  await writeFile(tmp, text, 'utf8')
  await rename(tmp, path)
}

/**
 * Saving runs in the dev server rather than a separate backend: it is already
 * a node process with access to the repo, and the documents live in the repo.
 * A production build has no server and therefore no save, which is the correct
 * trade for a local authoring tool.
 */
function docsApi(): Plugin {
  return {
    name: 'whippan-docs-api',
    configureServer(server: ViteDevServer) {
      server.middlewares.use('/api/doc/', async (req, res) => {
        const send = (code: number, payload: unknown) => {
          res.statusCode = code
          res.setHeader('content-type', 'application/json')
          res.end(JSON.stringify(payload))
        }
        // the slug is the whole path after /api/doc/ and must not escape it
        const slug = decodeURIComponent((req.url ?? '').replace(/^\/+/, '').split('?')[0])
        if (!/^[a-z0-9][a-z0-9-]*$/i.test(slug)) return send(400, { error: 'bad slug' })

        if (req.method === 'GET') {
          try {
            const [stage, anim] = await Promise.all([
              locate(slug, 'stage').then(p => readFile(p, 'utf8')),
              locate(slug, 'anim').then(p => readFile(p, 'utf8')),
            ])
            return send(200, { stage: JSON.parse(stage), anim: JSON.parse(anim) })
          } catch (e) {
            return send(404, { error: String(e) })
          }
        }

        if (req.method !== 'POST') return send(405, { error: 'use POST' })

        try {
          const parsed = JSON.parse(await body(req))
          const { stage, anim } = parsed as { stage?: unknown; anim?: unknown }
          // refuse anything that is not recognisably a document, so a bug in
          // the client cannot flatten a film into {}
          if (!stage || typeof stage !== 'object'
              || !Array.isArray((stage as { scenes?: unknown }).scenes)
              || !(stage as { scenes: unknown[] }).scenes.length) {
            return send(422, { error: 'stage has no scenes' })
          }
          if (!anim || typeof anim !== 'object'
              || !Array.isArray((anim as { tracks?: unknown }).tracks)) {
            return send(422, { error: 'anim has no tracks' })
          }
          const stagePath = await locate(slug, 'stage')
          const animPath = await locate(slug, 'anim')
          await writeAtomic(stagePath,
            JSON.stringify(stage, null, await indentOf(stagePath)))
          await writeAtomic(animPath,
            JSON.stringify(anim, null, await indentOf(animPath)))
          return send(200, { ok: true, slug })
        } catch (e) {
          return send(500, { error: String(e) })
        }
      })
    },
  }
}

export default defineConfig({
  // the wasm glue must stay unbundled, and public/ symlinks out to the repo
  optimizeDeps: { exclude: ['@whippan/engine-web'] },
  plugins: [react(), tailwindcss(), docsApi()],
  server: { port: 8902, fs: { allow: ['../..'] } },
})
