#!/usr/bin/env python3
# inline nucleo svgs as react components. stroke/fill colors become
# currentColor so the ui tints them; native viewBox is kept.
import re

LIB = "/Users/mintu/coding/portfolio/ui/tools/icons"
ICONS = {
    "Pointer": "ui/pointer.svg",
    "TextTool": "ui/text-tool-2.svg",
    "Shapes": "ui/shapes.svg",
    "Picture": "ui/image.svg",
    "PenNib": "ui/pen-nib-3.svg",
    "Film": "ui/film.svg",
    "Floppy": "core/floppy-disk.svg",
    "ZoomIn": "core/magnifier-plus.svg",
    "ZoomOut": "core/magnifier-minus.svg",
}

out = ["// generated by tools/gen-icons.py from the nucleo library — do not hand-edit",
       "// (play/pause are hand-drawn: nucleo has no plain transport triangles)", ""]
for name, rel in ICONS.items():
    src = open(f"{LIB}/{rel}").read()
    vb = re.search(r'viewBox="([^"]+)"', src).group(1)
    inner = re.sub(r"^.*?<svg[^>]*>", "", src, flags=re.S)
    inner = re.sub(r"</svg>.*$", "", inner, flags=re.S)
    inner = re.sub(r"<title>.*?</title>", "", inner, flags=re.S)
    inner = inner.replace('stroke="#000"', 'stroke="currentColor"')
    inner = inner.replace('fill="#000"', 'fill="currentColor"')
    # jsx-ify attribute names
    for a, b in [("stroke-linecap", "strokeLinecap"), ("stroke-linejoin", "strokeLinejoin"),
                 ("stroke-width", "strokeWidth"), ("stroke-miterlimit", "strokeMiterlimit"),
                 ("data-color", "data-color"), ("fill-rule", "fillRule"), ("clip-rule", "clipRule")]:
        inner = inner.replace(a, b)
    out.append(f"export const {name} = ({{ size = 16, ...p }}) => (")
    out.append(f'  <svg width={{size}} height={{size}} viewBox="{vb}" {{...p}}>{inner.strip()}</svg>')
    out.append(")")
    out.append("")

out += [
    "export const Play = ({ size = 16, ...p }) => (",
    '  <svg width={size} height={size} viewBox="0 0 16 16" {...p}>',
    '    <path d="M4 2.8v10.4c0 .6.7 1 1.2.7l8.3-5.2c.5-.3.5-1 0-1.3L5.2 2.1c-.5-.3-1.2 0-1.2.7z" fill="currentColor" />',
    "  </svg>",
    ")",
    "",
    "export const Pause = ({ size = 16, ...p }) => (",
    '  <svg width={size} height={size} viewBox="0 0 16 16" {...p}>',
    '    <rect x="3" y="2.5" width="3.4" height="11" rx="1" fill="currentColor" />',
    '    <rect x="9.6" y="2.5" width="3.4" height="11" rx="1" fill="currentColor" />',
    "  </svg>",
    ")",
]
open("src/icons.jsx", "w").write("\n".join(out) + "\n")
print("wrote src/icons.jsx,", len(ICONS) + 2, "icons")
