// generated by tools/gen-icons.py from the nucleo library — do not hand-edit
// (play/pause are hand-drawn: nucleo has no plain transport triangles)

export const Pointer = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 12 12" {...p}><path d="m1.455.814l9.367,3.422c.447.163.434.801-.019.946l-4.258,1.363-1.363,4.258c-.145.454-.782.467-.946.019L.814,1.455c-.146-.399.242-.787.641-.641Z" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></path></svg>
)

export const TextTool = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 18 18" {...p}><path d="M16.25,12v.75c0,1.105-.895,2-2,2H3.75c-1.105,0-2-.895-2-2v-.75" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></path><path d="M1.75,6v-.75c0-1.105,.895-2,2-2H14.25c1.105,0,2,.895,2,2v.75" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></path><polyline points="11.798 12.25 9.068 5.75 8.932 5.75 6.202 12.25" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" data-color="color-2"></polyline><line x1="6.832" y1="10.75" x2="11.168" y2="10.75" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" data-color="color-2"></line><circle cx="1.75" cy="9" r=".75" fill="currentColor" data-stroke="none"></circle><circle cx="16.25" cy="9" r=".75" fill="currentColor" data-stroke="none"></circle></svg>
)

export const Shapes = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 18 18" {...p}><circle cx="13.5" cy="6" r="3.25" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" data-color="color-2"></circle><rect x="4.75" y="10.75" width="5.5" height="5.5" rx="1" ry="1" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></rect><path d="M3.818,1.99L1.189,6.498c-.194,.333,.046,.752,.432,.752H6.879c.386,0,.626-.419,.432-.752L4.682,1.99c-.193-.331-.671-.331-.864,0Z" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></path></svg>
)

export const Picture = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 12 12" {...p}><path d="m2.32,10.516l4.723-4.723c.391-.391,1.024-.391,1.414,0l2.293,2.293" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" data-color="color-2"></path><circle cx="4" cy="4" r="1" fill="currentColor" strokeWidth="0" data-color="color-2"></circle><rect x="1.25" y="1.25" width="9.5" height="9.5" rx="2" ry="2" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></rect></svg>
)

export const PenNib = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 18 18" {...p}><path d="M10 9.54501L5.07001 14.475" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" data-color="color-2" fill="none"></path> <path d="M1.86329 13.6331C1.06149 12.8389 0.825792 12.1376 0.776992 11.604C0.602992 9.68 2.75199 8.65301 2.73799 6.50601C2.72899 5.12901 1.83399 4.01499 1.10399 3.30399" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" data-color="color-2" fill="none"></path> <path d="M15.241 8.05701L13.649 12.553C13.532 12.883 13.252 13.128 12.909 13.198L5.75203 14.679C5.22403 14.788 4.75603 14.321 4.86603 13.793L6.34703 6.63599C6.41803 6.29299 6.66303 6.013 6.99203 5.896L11.488 4.30399" stroke="black" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none"></path> <path d="M11.496 2.29599L11.195 2.59698C10.804 2.98798 10.804 3.62099 11.195 4.01099L13.364 6.17999L15.533 8.349C15.924 8.74 16.557 8.74 16.947 8.349L17.248 8.048" stroke="black" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none"></path> <path d="M10 10.295C10.4142 10.295 10.75 9.95901 10.75 9.54501C10.75 9.13101 10.4142 8.79501 10 8.79501C9.5858 8.79501 9.25 9.13101 9.25 9.54501C9.25 9.95901 9.5858 10.295 10 10.295Z" fill="currentColor" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" data-color="color-2"></path></svg>
)

export const Film = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 18 18" {...p}><line x1="9" y1="6.25" x2="9" y2="11.75" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" data-color="color-2"></line><line x1="1.75" y1="6.25" x2="16.25" y2="6.25" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></line><line x1="1.75" y1="11.75" x2="16.25" y2="11.75" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></line><line x1="9" y1="11.75" x2="9" y2="15.25" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></line><line x1="9" y1="2.75" x2="9" y2="6.25" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></line><line x1="5.25" y1="2.75" x2="5.25" y2="6.25" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></line><line x1="12.75" y1="2.75" x2="12.75" y2="6.25" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></line><line x1="5.25" y1="11.75" x2="5.25" y2="15.25" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></line><line x1="12.75" y1="11.75" x2="12.75" y2="15.25" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></line><rect x="1.75" y="2.75" width="14.5" height="12.5" rx="2" ry="2" transform="translate(18 18) rotate(180)" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"></rect></svg>
)

export const Floppy = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" {...p}><polyline points="7 17 7 13 17 13 17 17" fill="none" stroke="currentColor" strokeLinecap="square" strokeMiterlimit="10" strokeWidth="2" data-color="color-2"></polyline><path d="m19,21H5c-1.105,0-2-.895-2-2V5c0-1.105.895-2,2-2h11l5,5v11c0,1.105-.895,2-2,2Z" fill="none" stroke="currentColor" strokeLinecap="square" strokeMiterlimit="10" strokeWidth="2"></path><line x1="15" y1="7" x2="15" y2="9" fill="none" stroke="currentColor" strokeLinecap="square" strokeMiterlimit="10" strokeWidth="2" data-color="color-2"></line></svg>
)

export const ZoomIn = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" {...p}><line x1="20.5" y1="20.5" x2="15" y2="15" fill="none" stroke="currentColor" strokeLinecap="square" strokeMiterlimit="10" strokeWidth="2" data-color="color-2"></line><circle cx="10" cy="10" r="7" fill="none" stroke="currentColor" strokeLinecap="square" strokeMiterlimit="10" strokeWidth="2"></circle><line x1="10" y1="13" x2="10" y2="7" fill="none" stroke="currentColor" strokeLinecap="square" strokeMiterlimit="10" strokeWidth="2" data-color="color-2"></line><line x1="7" y1="10" x2="13" y2="10" fill="none" stroke="currentColor" strokeLinecap="square" strokeMiterlimit="10" strokeWidth="2" data-color="color-2"></line></svg>
)

export const ZoomOut = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" {...p}><line x1="20.5" y1="20.5" x2="15" y2="15" fill="none" stroke="currentColor" strokeLinecap="square" strokeMiterlimit="10" strokeWidth="2" data-color="color-2"></line><circle cx="10" cy="10" r="7" fill="none" stroke="currentColor" strokeLinecap="square" strokeMiterlimit="10" strokeWidth="2"></circle><line x1="7" y1="10" x2="13" y2="10" fill="none" stroke="currentColor" strokeLinecap="square" strokeMiterlimit="10" strokeWidth="2" data-color="color-2"></line></svg>
)

export const Play = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 16 16" {...p}>
    <path d="M4 2.8v10.4c0 .6.7 1 1.2.7l8.3-5.2c.5-.3.5-1 0-1.3L5.2 2.1c-.5-.3-1.2 0-1.2.7z" fill="currentColor" />
  </svg>
)

export const Pause = ({ size = 16, ...p }) => (
  <svg width={size} height={size} viewBox="0 0 16 16" {...p}>
    <rect x="3" y="2.5" width="3.4" height="11" rx="1" fill="currentColor" />
    <rect x="9.6" y="2.5" width="3.4" height="11" rx="1" fill="currentColor" />
  </svg>
)
