import { access, mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import { join, resolve, sep } from 'node:path'
import type { DocStore, FilmDoc, FilmEntry } from './types.js'

/**
 * Films on a filesystem: the repo checkout in development, a mounted volume in
 * a container. Two roots because the existing library is split — reproductions
 * in the root, engine primitives in examples/ — and a save has to land on the
 * file it was read from.
 */
export class FsStore implements DocStore {
  private readonly roots: string[]

  constructor(private readonly base: string) {
    this.roots = [resolve(base), resolve(base, 'examples')]
  }

  /** never let a slug escape the configured roots, whatever validation upstream did */
  private safe(root: string, name: string): string {
    const path = resolve(root, name)
    if (path !== root && !path.startsWith(root + sep)) {
      throw new Error('path escapes the store')
    }
    return path
  }

  private async locate(slug: string, kind: 'stage' | 'anim'): Promise<string> {
    const name = `${slug}.${kind}.json`
    for (const root of this.roots) {
      const path = this.safe(root, name)
      try {
        await access(path)
        return path
      } catch { /* try the next root */ }
    }
    return this.safe(this.roots[0], name)
  }

  /**
   * Reuse a file's existing indent. The library was generated by more than one
   * script and is not uniform, so rewriting with a fixed indent would turn a
   * one-value edit into a whole-file diff.
   */
  private static async indentOf(path: string, fallback = 1): Promise<number> {
    try {
      const head = (await readFile(path, 'utf8')).slice(0, 200)
      const m = head.match(/^\{\r?\n( +)"/)
      return m ? m[1].length : fallback
    } catch {
      return fallback
    }
  }

  /** temp file then rename, so an interrupted write cannot truncate a film */
  private static async writeAtomic(path: string, text: string): Promise<void> {
    const tmp = `${path}.tmp`
    await writeFile(tmp, text, 'utf8')
    await rename(tmp, path)
  }

  async list(): Promise<FilmEntry[]> {
    const path = this.safe(this.roots[1], 'index.json')
    const raw = await readFile(path, 'utf8')
    return JSON.parse(raw) as FilmEntry[]
  }

  async has(slug: string): Promise<boolean> {
    try {
      await access(await this.locate(slug, 'stage'))
      return true
    } catch {
      return false
    }
  }

  async get(slug: string): Promise<FilmDoc | null> {
    try {
      const [stage, anim] = await Promise.all([
        this.locate(slug, 'stage').then(p => readFile(p, 'utf8')),
        this.locate(slug, 'anim').then(p => readFile(p, 'utf8')),
      ])
      return { stage: JSON.parse(stage), anim: JSON.parse(anim) }
    } catch {
      return null
    }
  }

  async put(slug: string, doc: FilmDoc): Promise<void> {
    await mkdir(this.roots[0], { recursive: true })
    const stagePath = await this.locate(slug, 'stage')
    const animPath = await this.locate(slug, 'anim')
    await FsStore.writeAtomic(
      stagePath, JSON.stringify(doc.stage, null, await FsStore.indentOf(stagePath)))
    await FsStore.writeAtomic(
      animPath, JSON.stringify(doc.anim, null, await FsStore.indentOf(animPath)))
  }

  get description(): string {
    return `fs:${join(this.base)}`
  }
}
